/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pistacarrera;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author KEVIN SANCHEZ
 */
public class Pista extends javax.swing.JFrame {

    Cronometro c7;

    PistaCarrera c2;
    PistaCarrera c1;
    PistaCarrera c3;
    PistaCarrera c4;
    static int segundos = 0;
    static int minutos = 0;
    static boolean iniciar;
    ArrayList<Auto> ordenLlegada = new ArrayList<>();
    //ArrayList<String> ordenLlegada1 = new ArrayList<>();

    /**
     * Creates new form Pista
     */
    public Pista() {
        initComponents();
        setLocationRelativeTo(null);
        jInternalFrame1.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.jInternalFrame1.getUI();
        bui.setNorthPane(null);
        c1 = new PistaCarrera(carro1, this, ordenLlegada, "Azul");
        c2 = new PistaCarrera(carro2, this, ordenLlegada, "Rojo");
        c3 = new PistaCarrera(carro3, this, ordenLlegada, "Verde");
        c4 = new PistaCarrera(carro4, this, ordenLlegada, "Amarillo");
        c7 = new Cronometro(lbTiempo);

    }

    public JLabel getCarrro1() {
        return carro1;
    }

    public JLabel getCarrr2() {
        return carro2;
    }

    public JLabel getCarrr3() {
        return carro3;
    }

    public JLabel getCarrr4() {
        return carro4;
    }

    public JLabel getBarrera() {
        return barrera;
    }

    public JLabel getTiempo() {
        return lbTiempo;
    }

    public JLabel setTiempo() {
        return lbTiempo;
    }

    public void parar() {
        c1.star2();
        c3.star2();
        c4.star2();
        c2.star2();
        c7.parar();
    }

    public void pararReloj() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        lbTiempo = new javax.swing.JLabel();
        barrera = new javax.swing.JLabel();
        carro2 = new necesario.RSLabelImage();
        carro3 = new necesario.RSLabelImage();
        carro4 = new necesario.RSLabelImage();
        rSLabelImage3 = new necesario.RSLabelImage();
        carro1 = new necesario.RSLabelImage();
        rSLabelImage1 = new necesario.RSLabelImage();
        btnIniciar = new org.edisoncor.gui.button.ButtonAction();
        btnPausar = new org.edisoncor.gui.button.ButtonAction();
        btnReanudar = new org.edisoncor.gui.button.ButtonAction();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame1.setFocusTraversalPolicyProvider(true);
        jInternalFrame1.setFocusable(false);
        jInternalFrame1.setInheritsPopupMenu(true);
        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbTiempo.setBackground(new java.awt.Color(0, 0, 0));
        lbTiempo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTiempo.setForeground(new java.awt.Color(255, 255, 255));
        lbTiempo.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(lbTiempo)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTiempo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jInternalFrame1.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        panelRound1.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, -1));
        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame1.getAccessibleContext().setAccessibleParent(this);

        barrera.setBackground(new java.awt.Color(204, 0, 0));
        barrera.setOpaque(true);
        panelRound1.add(barrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 30, 440));

        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1)-PhotoRoom.png-PhotoRoom (3).png"))); // NOI18N
        panelRound1.add(carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 70));

        carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1)-PhotoRoom.png-PhotoRoom (2).png"))); // NOI18N
        panelRound1.add(carro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 70));

        carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1)-PhotoRoom.png-PhotoRoom.png"))); // NOI18N
        panelRound1.add(carro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, 70));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1254769820-170667a (1).jpg"))); // NOI18N
        panelRound1.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 800, 210));

        carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pixel (1) (2)-PhotoRoom.png-PhotoRoom.png"))); // NOI18N
        panelRound1.add(carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 70));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1254769820-170667a.jpg"))); // NOI18N
        panelRound1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 800, 220));

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panelRound1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        btnPausar.setText("PAUSAR");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });
        panelRound1.add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        btnReanudar.setText("REANUDAR");
        btnReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReanudarActionPerformed(evt);
            }
        });
        panelRound1.add(btnReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piloto2-removebg-preview.png"))); // NOI18N
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        ordenLlegada.clear();
        c7.iniciar();
        if (iniciar == false) {
            c1.star1();
            c2.star1();
            c3.star1();
            c4.star1();
            iniciar = true;
        }
 
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed

        parar();
    }//GEN-LAST:event_btnPausarActionPerformed

    private void btnReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReanudarActionPerformed
        c1.renaudar();
        c3.renaudar();
        c4.renaudar();
        c2.renaudar();
        c7.iniciar();
    }//GEN-LAST:event_btnReanudarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barrera;
    public static org.edisoncor.gui.button.ButtonAction btnIniciar;
    private org.edisoncor.gui.button.ButtonAction btnPausar;
    private org.edisoncor.gui.button.ButtonAction btnReanudar;
    private necesario.RSLabelImage carro1;
    private necesario.RSLabelImage carro2;
    private necesario.RSLabelImage carro3;
    private necesario.RSLabelImage carro4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbTiempo;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private necesario.RSLabelImage rSLabelImage1;
    private necesario.RSLabelImage rSLabelImage3;
    // End of variables declaration//GEN-END:variables
}
