/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pistacarrera;

import javax.swing.JLabel;

/**
 *
 * @author KEVIN SANCHEZ
 */
public class Pista extends javax.swing.JFrame {

    PistaCarrera c2;
    PistaCarrera c1;
    PistaCarrera c3;
    PistaCarrera c4;
    static int segundos=0;
    static int minutos=0;
    static boolean iniciar=true;

    /**
     * Creates new form Pista
     */
    public Pista() {
        initComponents();
        setLocationRelativeTo(null);
        c1 = new PistaCarrera(carro1, this);
        c2 = new PistaCarrera(carro2, this);
        c3 = new PistaCarrera(carro3, this);
        c4 = new PistaCarrera(carro4, this);
    }

    public JLabel getCarrro1() {
        return carro1;
    }

    public JLabel getCarrr2() {
        return carro2;
    }

    public JLabel getCarrr3() {
        return carro3;
    }

    public JLabel getCarrr4() {
        return carro4;
    }

    public JLabel getBarrera() {
        return barrera;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        barrera = new javax.swing.JLabel();
        carro2 = new necesario.RSLabelImage();
        carro3 = new necesario.RSLabelImage();
        carro4 = new necesario.RSLabelImage();
        rSLabelImage3 = new necesario.RSLabelImage();
        carro1 = new necesario.RSLabelImage();
        rSLabelImage1 = new necesario.RSLabelImage();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction2 = new org.edisoncor.gui.button.ButtonAction();
        lbTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barrera.setBackground(new java.awt.Color(204, 0, 0));
        barrera.setOpaque(true);
        panelRound1.add(barrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 30, 440));

        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1)-PhotoRoom.png-PhotoRoom (3).png"))); // NOI18N
        panelRound1.add(carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 70));

        carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1)-PhotoRoom.png-PhotoRoom (2).png"))); // NOI18N
        panelRound1.add(carro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 70));

        carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1)-PhotoRoom.png-PhotoRoom.png"))); // NOI18N
        panelRound1.add(carro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, 70));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1254769820-170667a (1).jpg"))); // NOI18N
        panelRound1.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 800, 220));

        carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pixel (1) (2)-PhotoRoom.png-PhotoRoom.png"))); // NOI18N
        panelRound1.add(carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 70));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1254769820-170667a.jpg"))); // NOI18N
        panelRound1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 800, 220));

        buttonAction1.setText("INICIAR");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });
        panelRound1.add(buttonAction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        buttonAction2.setText("PAUSAR");
        buttonAction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction2ActionPerformed(evt);
            }
        });
        panelRound1.add(buttonAction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        lbTiempo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTiempo.setForeground(new java.awt.Color(255, 255, 255));
        lbTiempo.setText("00:00");
        panelRound1.add(lbTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        c1.star1();
        c2.star1();
        c3.star1();
        c4.star1();


    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void buttonAction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction2ActionPerformed
        c1.star2();
        c3.star2();
        c4.star2();
        c2.star2();


    }//GEN-LAST:event_buttonAction2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barrera;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonAction buttonAction2;
    private necesario.RSLabelImage carro1;
    private necesario.RSLabelImage carro2;
    private necesario.RSLabelImage carro3;
    private necesario.RSLabelImage carro4;
    private javax.swing.JLabel lbTiempo;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private necesario.RSLabelImage rSLabelImage1;
    private necesario.RSLabelImage rSLabelImage3;
    // End of variables declaration//GEN-END:variables
}
