/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pistacarrera;

import javax.swing.JLabel;

/**
 *
 * @author KEVIN SANCHEZ
 */
public class Pista extends javax.swing.JFrame {

    /**
     * Creates new form Pista
     */
    public Pista() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public JLabel getCarrro1() {
        return carro1;
    }

    public JLabel getCarrr2() {
        return carro2;
    }

    public JLabel getCarrr3() {
        return carro3;
    }

    public JLabel getCarrr4() {
        return carro4;
    }

    public JLabel getBarrera() {
        return barrera;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        barrera = new javax.swing.JLabel();
        carro2 = new necesario.RSLabelImage();
        carro3 = new necesario.RSLabelImage();
        carro4 = new necesario.RSLabelImage();
        rSLabelImage3 = new necesario.RSLabelImage();
        carro1 = new necesario.RSLabelImage();
        rSLabelImage1 = new necesario.RSLabelImage();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barrera.setBackground(new java.awt.Color(204, 0, 0));
        barrera.setOpaque(true);
        panelRound1.add(barrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 30, 440));

        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche-de-carreras (1).png"))); // NOI18N
        panelRound1.add(carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 110));

        carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro-deportivo (1).png"))); // NOI18N
        panelRound1.add(carro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 110));

        carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro-deportivo.png"))); // NOI18N
        panelRound1.add(carro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 120, 130));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1254769820-170667a (1).jpg"))); // NOI18N
        panelRound1.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 800, 220));

        carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche-de-carreras.png"))); // NOI18N
        panelRound1.add(carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 120));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1254769820-170667a.jpg"))); // NOI18N
        panelRound1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 800, 220));

        buttonAction1.setText("INICIAR");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });
        panelRound1.add(buttonAction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        carro1.setLocation(80,carro1.getLocation().y);
        carro2.setLocation(80, carro2.getLocation().y);
        carro3.setLocation(80, carro3.getLocation().y);
        carro4.setLocation(80, carro4.getLocation().y);
        PistaCarrera r = new PistaCarrera(carro1, this);
        PistaCarrera r1 = new PistaCarrera(carro2, this);
        PistaCarrera r2 = new PistaCarrera(carro3, this);
        PistaCarrera r3 = new PistaCarrera(carro4, this);
        r.start();
        r1.start();
        r2.start();
        r3.start();

    }//GEN-LAST:event_buttonAction1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barrera;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private necesario.RSLabelImage carro1;
    private necesario.RSLabelImage carro2;
    private necesario.RSLabelImage carro3;
    private necesario.RSLabelImage carro4;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private necesario.RSLabelImage rSLabelImage1;
    private necesario.RSLabelImage rSLabelImage3;
    // End of variables declaration//GEN-END:variables
}
