/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pistacarrera;

/**
 *
 * @author KEVIN SANCHEZ
 */
public class Podio extends javax.swing.JFrame {

    /**
     * Creates new form Podio
     */
    public Podio() {
        initComponents();
        setLocationRelativeTo(null);
        if (PistaCarrera.ordenLlegada.size() == 4){
            for (int i = 0; i < PistaCarrera.ordenLlegada.size(); i++) {
                System.out.println("Podio" + PistaCarrera.ordenLlegada.get(i));
                if (i==0) {
                    lbPrimer.setText(PistaCarrera.ordenLlegada.get(i).getNombre()); 
                    lbTiempo1.setText(PistaCarrera.ordenLlegada.get(i).getNombre()+" "+PistaCarrera.ordenLlegada.get(i).getTiempo());
                }else if (i==1) {
                     lbSegundo.setText(PistaCarrera.ordenLlegada.get(i).getNombre()); 
                     lbTiempo2.setText(PistaCarrera.ordenLlegada.get(i).getNombre()+" "+PistaCarrera.ordenLlegada.get(i).getTiempo());
                }else if (i==2){
                    lbTercero.setText(PistaCarrera.ordenLlegada.get(i).getNombre());
                    lbTiempo3.setText(PistaCarrera.ordenLlegada.get(i).getNombre()+" "+PistaCarrera.ordenLlegada.get(i).getTiempo());
                }else if(i==3){
                    
                    //System.out.println(PistaCarrera.ordenLlegada.get(i).getNombre());
                    lbTiempo4.setText(PistaCarrera.ordenLlegada.get(3).getNombre()+" "+PistaCarrera.ordenLlegada.get(3).getTiempo());
                
                }
                
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbPrimer = new javax.swing.JLabel();
        lbSegundo = new javax.swing.JLabel();
        lbTercero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonRound1 = new org.edisoncor.gui.button.ButtonRound();
        lbTiempo1 = new javax.swing.JLabel();
        lbTiempo2 = new javax.swing.JLabel();
        lbTiempo3 = new javax.swing.JLabel();
        lbTiempo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPrimer.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        lbPrimer.setForeground(new java.awt.Color(255, 255, 0));
        lbPrimer.setText("jLabel1");
        lbPrimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbPrimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 90, -1));

        lbSegundo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        lbSegundo.setForeground(new java.awt.Color(162, 162, 161));
        lbSegundo.setText("jLabel2");
        jPanel1.add(lbSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, -1));

        lbTercero.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        lbTercero.setForeground(new java.awt.Color(244, 188, 75));
        lbTercero.setText("jLabel3");
        jPanel1.add(lbTercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 100, 20));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ESTADÍSTICAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/podio-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 320));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/win-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 340, 50));

        buttonRound1.setBackground(new java.awt.Color(204, 0, 0));
        buttonRound1.setText("REGRESAR");
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        lbTiempo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTiempo1.setText("jLabel1");
        jPanel1.add(lbTiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        lbTiempo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTiempo2.setText("jLabel2");
        jPanel1.add(lbTiempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        lbTiempo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTiempo3.setText("jLabel3");
        jPanel1.add(lbTiempo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        lbTiempo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTiempo4.setText("jLabel6");
        jPanel1.add(lbTiempo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        System.exit(0);
           
    }//GEN-LAST:event_buttonRound1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Podio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Podio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound buttonRound1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPrimer;
    private javax.swing.JLabel lbSegundo;
    private javax.swing.JLabel lbTercero;
    private javax.swing.JLabel lbTiempo1;
    private javax.swing.JLabel lbTiempo2;
    private javax.swing.JLabel lbTiempo3;
    private javax.swing.JLabel lbTiempo4;
    // End of variables declaration//GEN-END:variables
}
